#ifndef __FILE_PATTERN_SOURCE_INCLUDED__
#define __FILE_PATTERN_SOURCE_INCLUDED__

#include "streamed_analysys.hpp"

/**Pattern producer, reading patterns from the file, generated by the standalone searched.
 */
class PatternSource: public AbstractPatternSource{
  std::istream &stream;
  static const size_t buf_size=2048;
  char line_buffer[buf_size];
  bool closed;
public:
  PatternSource( std::istream &s ): stream(s), closed(false){};
  virtual bool get( Pattern & p, int& g );
  virtual bool is_closed();
};



#endif
